# Generated by Django 4.2.5 on 2023-10-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpf_model', '0001_initial'),
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpf_model.cpf'),
        ),
    ]
