# Generated by Django 4.2.5 on 2023-10-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco_model', '0001_initial'),
        ('user_api', '0002_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='endereco_model.endereco'),
        ),
    ]
